# Adafruit QTPY format ESP32C3 with AHT20 temperature and humidity sensor connected via i2c.
# microcontroller: https://www.adafruit.com/product/5405
# temp/humidity sensor: https://www.adafruit.com/product/4566

esphome:
  name: esp32c3-qtpy-aht20
   platformio_options:
    board_build.flash_mode: dio  # This is critical!

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: VERY_VERBOSE
  # hardware_uart: USB_CDC

# Enable Home Assistant API
api:
  encryption:
    key: "key here"

ota:
  password: "password here"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ssid"
    password: "password"

i2c:
  - id: stemma
    sda: GPIO5
    scl: GPIO6
    scan: true

sensor:
  - platform: aht10
    i2c_id: stemma
    address: 0x38
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s
